// NECESITAMOS EXPRESS POR ESO LA INSTANCIAMOS
// DESPUES
// INSTANCIAMOS RUTA
const express = require('express');
const ruta = express.Router();
const {seguridad} = require('../middleware/seguridad');


// LA RUTA NECESITA EL METODO AL CUAL SE VA A VINCULAR
// IMPORTO LOS METODOS CONTROLLER
const { login, getUsuario, registrarUsuario} = require('../controllers/usuario');

// CUANDO EL CONTROLLER SEA USUARIO/ QUIERO QUE DEVUELVA EL USUARIO QUE ESTE EN SESION
// POR ESO LLAMAMOS AL METODO CONTROLLER GETUSUARIO
ruta.get('/', seguridad, getUsuario);

//NECESITO QUE SE REGISTRE UN USUARIO Y ESO USA METODO POST
// POR ESO LLAMAMOS AL METODO CONTROLLER REGISTRARUSUARIO
ruta.post('/registrar', registrarUsuario);

//NECESITO QUE SE REGISTRE UN USUARIO Y ESO USA METODO POST
// POR ESO LLAMAMOS AL METODO CONTROLLER LOGIN
ruta.post('/login', login);

// AHORA TENGO QUE EXPORTAR LA RUTA QUE CONTIENE LOS METODOS CONTROLLERS Y LAS URL PARA CADA CASO
module.exports = ruta;

// AHORA DEBO REGISTRAR ESTAS RUTAS EN EL CORAZON DE MI PROYECTO SERVER.JS
//LUEGO REVISO EN MI BASE DE DATOS COMPASS ME CONECTO
// Y HABRA UN ERROR ME MOSTRARA EL PASSWORD DEBEMOS ENCRIPTARLA
//ESO LO HAGO EN LOS MODELS EN LA PROPIEDAD PASSWORD CON UN MIDDLEWARE